---
abstract: 'Automatically encode column values'
author:
  - 'Guillermo Roditi (groditi) <groditi@cpan.org>'
build_requires:
  DBD::SQLite: 0
  Dir::Self: 0
  ExtUtils::MakeMaker: 6.36
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-EncodedColumn
no_index:
  directory:
    - inc
    - t
recommends:
  Crypt::OpenPGP: 0
  Digest: 0
  Digest::SHA: 0
  Math::Pari: 0
requires:
  DBIx::Class: '0.06002'
  Encode: 0
  Sub::Name: '0.04'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/wreis/DBIx-Class-EncodedColumn.git
version: '0.00013'
