---
abstract: 'Automatically encode column values'
author:
  - 'Guillermo Roditi (groditi) <groditi@cpan.org>'
build_requires:
  DBD::SQLite: 0
  Dir::Self: 0
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-EncodedColumn
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.06002
  Sub::Name: 0.04
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/wreis/DBIx-Class-EncodedColumn.git
version: 0.00011
